"use client";
import React, { useEffect, useState } from 'react';
import { firebaseBridge } from '../lib/firebase-bridge';
import { useLanguage } from '../lib/LanguageContext';

// Rodape que so existe no papel.
//
// A rotina impressa e a unica superficie visivel do produto: ela fica na
// cozinha e e lida por quem passa — avo, baba, terapeuta domiciliar, a outra
// mae que veio buscar o filho. O rodape existe para que essa leitura tenha
// para onde ir. Discreto de proposito: se parecer anuncio, a familia corta
// com a tesoura e a alavanca morre.
//
// Duas variantes:
//  - "familia": QR do link de indicacao daquela conta (os dois lados ganham).
//  - "profissional": QR do portal, para o colega que recebeu o relatorio.

type Props =
  | { variant: 'familia' }
  | { variant: 'profissional'; qrSvg?: string | null; url?: string | null };

// Uma requisicao por pagina, mesmo com varios rodapes montados.
let cache: Promise<any> | null = null;
function statusIndicacao() {
  if (!cache) {
    cache = firebaseBridge.auth.getReferralStatus().catch(() => null);
  }
  return cache;
}

export function PrintFooter(props: Props) {
  const { locale } = useLanguage();
  const [familia, setFamilia] = useState<{ qrSvg?: string; link?: string; diasPorIndicacao?: number } | null>(null);

  useEffect(() => {
    if (props.variant !== 'familia') return;
    let vivo = true;
    statusIndicacao().then((s) => { if (vivo && s) setFamilia(s); });
    return () => { vivo = false; };
  }, [props.variant]);

  const svg = props.variant === 'familia' ? familia?.qrSvg : props.qrSvg;
  const url =
    props.variant === 'familia'
      ? familia?.link
      : props.url || 'teacolher.online/therapist';

  // Sem QR o rodape ainda vale: a marca no papel e metade da alavanca.
  const dias = familia?.diasPorIndicacao ?? 30;

  const chamada =
    props.variant === 'familia'
      ? locale === 'en'
        ? `Scan it: whoever signs up with this code gets ${dias} days of Premium — and so do you.`
        : locale === 'es'
        ? `Escanéelo: quien se registre con este código gana ${dias} días de Premium — y usted también.`
        : `Aponte a câmera: quem se cadastrar por este código ganha ${dias} dias de Premium — e você também.`
      : locale === 'en'
      ? 'Free panel for therapists and schools — scan to open the portal.'
      : locale === 'es'
      ? 'Panel gratuito para terapeutas y escuelas — escanee para abrir el portal.'
      : 'Painel gratuito para terapeutas e escolas — aponte a câmera para abrir o portal.';

  const marca =
    props.variant === 'familia'
      ? locale === 'en'
        ? 'Routine built with TEAcolher'
        : locale === 'es'
        ? 'Rutina creada con TEAcolher'
        : 'Rotina montada no TEAcolher'
      : locale === 'en'
      ? 'Report generated by TEAcolher'
      : locale === 'es'
      ? 'Informe generado por TEAcolher'
      : 'Relatório gerado no TEAcolher';

  return (
    <div className="print-footer">
      {svg && (
        <div
          className="print-footer-qr"
          aria-hidden="true"
          dangerouslySetInnerHTML={{ __html: svg }}
        />
      )}
      <div className="print-footer-text">
        <span className="print-footer-brand">{marca}</span>
        <span className="print-footer-url">{(url || '').replace(/^https?:\/\//, '')}</span>
        <span className="print-footer-call">{chamada}</span>
      </div>
    </div>
  );
}
